/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDownloadsRouteImport } from './routes/_app/downloads'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppStatisticsRouteImport } from './routes/_app/statistics'
import { Route as AppUpdatesRouteImport } from './routes/_app/updates'
import { Route as WatchEpisodeIdRouteImport } from './routes/watch/$episodeId'
import { Route as AppAnimeAnimeIdRouteImport } from './routes/_app/anime/$animeId'
import { Route as AppBrowseExtensionsRouteImport } from './routes/_app/browse/extensions'
import { Route as AppBrowseGlobalSearchRouteImport } from './routes/_app/browse/global-search'
import { Route as AppDevSpikeRouteImport } from './routes/_app/dev/spike'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings/$section'
import { Route as AppBrowseSourcesIndexRouteImport } from './routes/_app/browse/sources/index'
import { Route as AppBrowseSourcesSourceIdRouteImport } from './routes/_app/browse/sources/$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDownloadsRoute = AppDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdatesRoute = AppUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppRoute,
} as any)
const WatchEpisodeIdRoute = WatchEpisodeIdRouteImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnimeAnimeIdRoute = AppAnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseExtensionsRoute = AppBrowseExtensionsRouteImport.update({
  id: '/browse/extensions',
  path: '/browse/extensions',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseGlobalSearchRoute = AppBrowseGlobalSearchRouteImport.update({
  id: '/browse/global-search',
  path: '/browse/global-search',
  getParentRoute: () => AppRoute,
} as any)
const AppDevSpikeRoute = AppDevSpikeRouteImport.update({
  id: '/dev/spike',
  path: '/dev/spike',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseSourcesIndexRoute = AppBrowseSourcesIndexRouteImport.update({
  id: '/browse/sources/',
  path: '/browse/sources/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseSourcesSourceIdRoute =
  AppBrowseSourcesSourceIdRouteImport.update({
    id: '/browse/sources/$sourceId',
    path: '/browse/sources/$sourceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof AppDownloadsRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/statistics': typeof AppStatisticsRoute
  '/updates': typeof AppUpdatesRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/anime/$animeId': typeof AppAnimeAnimeIdRoute
  '/browse/extensions': typeof AppBrowseExtensionsRoute
  '/browse/global-search': typeof AppBrowseGlobalSearchRoute
  '/dev/spike': typeof AppDevSpikeRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/browse/sources/$sourceId': typeof AppBrowseSourcesSourceIdRoute
  '/browse/sources/': typeof AppBrowseSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof AppDownloadsRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/statistics': typeof AppStatisticsRoute
  '/updates': typeof AppUpdatesRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/anime/$animeId': typeof AppAnimeAnimeIdRoute
  '/browse/extensions': typeof AppBrowseExtensionsRoute
  '/browse/global-search': typeof AppBrowseGlobalSearchRoute
  '/dev/spike': typeof AppDevSpikeRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/browse/sources/$sourceId': typeof AppBrowseSourcesSourceIdRoute
  '/browse/sources': typeof AppBrowseSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/downloads': typeof AppDownloadsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/updates': typeof AppUpdatesRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
  '/_app/anime/$animeId': typeof AppAnimeAnimeIdRoute
  '/_app/browse/extensions': typeof AppBrowseExtensionsRoute
  '/_app/browse/global-search': typeof AppBrowseGlobalSearchRoute
  '/_app/dev/spike': typeof AppDevSpikeRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/browse/sources/$sourceId': typeof AppBrowseSourcesSourceIdRoute
  '/_app/browse/sources/': typeof AppBrowseSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/history'
    | '/library'
    | '/statistics'
    | '/updates'
    | '/watch/$episodeId'
    | '/anime/$animeId'
    | '/browse/extensions'
    | '/browse/global-search'
    | '/dev/spike'
    | '/settings/$section'
    | '/browse/sources/$sourceId'
    | '/browse/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/history'
    | '/library'
    | '/statistics'
    | '/updates'
    | '/watch/$episodeId'
    | '/anime/$animeId'
    | '/browse/extensions'
    | '/browse/global-search'
    | '/dev/spike'
    | '/settings/$section'
    | '/browse/sources/$sourceId'
    | '/browse/sources'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/downloads'
    | '/_app/history'
    | '/_app/library'
    | '/_app/statistics'
    | '/_app/updates'
    | '/watch/$episodeId'
    | '/_app/anime/$animeId'
    | '/_app/browse/extensions'
    | '/_app/browse/global-search'
    | '/_app/dev/spike'
    | '/_app/settings/$section'
    | '/_app/browse/sources/$sourceId'
    | '/_app/browse/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/downloads': {
      id: '/_app/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AppDownloadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/updates': {
      id: '/_app/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AppUpdatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/anime/$animeId': {
      id: '/_app/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AppAnimeAnimeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/extensions': {
      id: '/_app/browse/extensions'
      path: '/browse/extensions'
      fullPath: '/browse/extensions'
      preLoaderRoute: typeof AppBrowseExtensionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/global-search': {
      id: '/_app/browse/global-search'
      path: '/browse/global-search'
      fullPath: '/browse/global-search'
      preLoaderRoute: typeof AppBrowseGlobalSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dev/spike': {
      id: '/_app/dev/spike'
      path: '/dev/spike'
      fullPath: '/dev/spike'
      preLoaderRoute: typeof AppDevSpikeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/sources/': {
      id: '/_app/browse/sources/'
      path: '/browse/sources'
      fullPath: '/browse/sources/'
      preLoaderRoute: typeof AppBrowseSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/sources/$sourceId': {
      id: '/_app/browse/sources/$sourceId'
      path: '/browse/sources/$sourceId'
      fullPath: '/browse/sources/$sourceId'
      preLoaderRoute: typeof AppBrowseSourcesSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDownloadsRoute: typeof AppDownloadsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppUpdatesRoute: typeof AppUpdatesRoute
  AppAnimeAnimeIdRoute: typeof AppAnimeAnimeIdRoute
  AppBrowseExtensionsRoute: typeof AppBrowseExtensionsRoute
  AppBrowseGlobalSearchRoute: typeof AppBrowseGlobalSearchRoute
  AppDevSpikeRoute: typeof AppDevSpikeRoute
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppBrowseSourcesSourceIdRoute: typeof AppBrowseSourcesSourceIdRoute
  AppBrowseSourcesIndexRoute: typeof AppBrowseSourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDownloadsRoute: AppDownloadsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppUpdatesRoute: AppUpdatesRoute,
  AppAnimeAnimeIdRoute: AppAnimeAnimeIdRoute,
  AppBrowseExtensionsRoute: AppBrowseExtensionsRoute,
  AppBrowseGlobalSearchRoute: AppBrowseGlobalSearchRoute,
  AppDevSpikeRoute: AppDevSpikeRoute,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppBrowseSourcesSourceIdRoute: AppBrowseSourcesSourceIdRoute,
  AppBrowseSourcesIndexRoute: AppBrowseSourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
