// Channel names only (no zod), so the sandboxed preload can allowlist them cheaply.
export const INVOKE_CHANNELS = [
  'app.getInfo',
  'app.getLocale',
  'app.openExternal',
  'window.minimize',
  'window.toggleMaximize',
  'window.close',
  'window.isMaximized',
  'settings.get',
  'settings.set',
  'dialog.pickFolder',
  'network.getStatus',
  /** Loads a ping endpoint with the network settings (NET-8). */
  'network.testConnection',
  'network.proxyPasswordInfo',
  'network.setProxyPassword',
  'incognito.get',
  'incognito.set',
  'backup.export',
  'backup.peek',
  'backup.import',
  /** The backup files in the backup folder, newest first. */
  'backup.list',
  /** Writes a backup into the backup folder right now (no dialog). */
  'backup.create',
  /** Reads a backup file from the list without applying it. */
  'backup.peekFile',
  'backup.folder',
  'backup.openFolder',
  'app.changelog',
  'requests.cancel',
  'extensions.list',
  'extensions.loadDevFolder',
  'extensions.removeDevFolder',
  'extensions.reload',
  'extensions.logs',
  'extensions.preferences',
  'extensions.setPreference',
  'extensions.available',
  'extensions.prepareInstall',
  'extensions.install',
  'extensions.update',
  'extensions.updateAll',
  'extensions.uninstall',
  'repos.list',
  'repos.preview',
  'repos.add',
  'repos.remove',
  'repos.refresh',
  'repos.setTrust',
  'sources.list',
  'sources.capabilities',
  'sources.filters',
  'sources.browse',
  /** The first page of Popular or Latest as last seen, to show while the real one loads; null when none. */
  'sources.browseCached',
  'sources.resolveUrl',
  'sources.setPinned',
  'anime.get',
  'anime.refresh',
  /** Saves the episode sort and filters of one anime; null goes back to the default view. */
  'anime.setEpisodeView',
  'episodes.list',
  'library.list',
  'library.count',
  /** How many anime are in no category (the "Default" tab). */
  'library.uncategorizedCount',
  'library.markWatched',
  'library.add',
  'library.remove',
  'library.setCategories',
  'library.migratePreview',
  'library.migrate',
  'categories.list',
  'categories.create',
  'categories.rename',
  'categories.delete',
  'categories.reorder',
  'categories.setAutoDownload',
  'episodes.markWatched',
  'episodes.markPrevious',
  'episodes.resetProgress',
  'watch.progress',
  'watch.continueTarget',
  'history.list',
  'history.delete',
  'history.clear',
  'playback.start',
  'playback.event',
  'playback.switchStream',
  'playback.close',
  'playback.keepAwake',
  /** The renderer reports which codecs Chromium can play, once at start (PLY-12). */
  'playback.reportCodecs',
  'downloads.list',
  'downloads.enqueue',
  'downloads.pause',
  'downloads.resume',
  'downloads.pauseAll',
  'downloads.resumeAll',
  'downloads.cancel',
  'downloads.remove',
  'downloads.retry',
  'downloads.reorder',
  /** Drops the failed downloads and their partial files. */
  'downloads.clearFailed',
  'downloads.storage',
  'downloads.changeFolder',
  /** Opens the download folder in the file manager. */
  'downloads.openFolder',
  /** Bytes the cover cache uses on disk. */
  'storage.cacheSize',
  /** Empties the cover cache; the library's permanent covers stay. */
  'storage.clearCache',
  'stats.overview',
  /** Forgets every watch session (Settings → Data). Progress, watched marks and history stay. */
  'stats.clear',
  'updates.list',
  'updates.count',
  'updates.check',
  /** Dismisses Updates entries without marking them watched; resolves to how many were dismissed. */
  'updates.markSeen',
  /** Dismisses every entry Updates shows now; resolves to how many. */
  'updates.markAllSeen',
  // Playback spike (phase 0). Only answered when the app runs with MATANE_SPIKE=1 or in development.
  'dev.seedLibrary',
  'spike.fixtures',
  'spike.start',
  'spike.stats',
  'spike.reset',
  'spike.report',
] as const;
export type InvokeChannel = (typeof INVOKE_CHANNELS)[number];

export const EVENT_CHANNELS = [
  'window.maximizeChanged',
  'settings.changed',
  /** A write touched these entities: queries tagged with them are stale. */
  'db.changed',
  'network.status',
  'incognito.changed',
  'extensions.log',
  'cloudflare.status',
  /** Progress of the active downloads, a few times a second. */
  'downloads.progress',
  'updates.status',
  /** Main asks the renderer to open a route (a clicked notification, the tray). */
  'app.navigate',
] as const;
export type EventChannel = (typeof EVENT_CHANNELS)[number];
